### ISSUE TITLE
Dredd/Gavel incorrectly validates response body as valid when a JSON schema contains definitions and $ref

### ISSUE THREAD

**Issue by jessedc** [apiaryio/dredd#254]
I have noticed that dredd incorrectly marks my API responses as valid if I supply a JSON Schema that uses "definitions" as [outlined here](http://spacetelescope.github.io/understanding-json-schema/structuring.html).

My server is returning the following JSON for a simple GET request:

``` json
{
    "address": {
        "street": "123 Test Street",
        "postcode": "12345"
    }
}
```

My API Blueprint has two test cases, one that validates the above JSON against a JSON Schema expecting the "address" object to contain three fields. The second request uses a JSON Schema that extracts the "address" object into a definition and references this with a JSON Pointer.

As expected the first request is failing with message `body: At '/address/country' Missing required property: country`. But the second request is happily passing.

```
# Test Endpoint [/api.php]

Tests the validity of server responses against json-schema.

## Schema with no definitions [GET]

+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema",
                "id": "schema-no-definitions",
                "type": "object",
                "properties": {
                    "address": {
                        "type": "object",
                        "properties": {
                            "street": {
                                "type": "string",
                                "minLength": 1
                            },
                            "postcode": {
                                "type": "string",
                                "minLength": 1
                            },
                            "country": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "street", "postcode", "country"
                        ]
                    }
                },
                "required" : [
                    "address"
                ]
            }

## Test schema with definitions [GET]

+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema",
                "id": "schema-definitions",
                "definitions": {
                    "addressItem": {
                        "type": "object",
                        "properties": {
                            "street": {
                                "type": "string",
                                "minLength": 1
                            },
                            "postcode": {
                                "type": "string",
                                "minLength": 1
                            },
                            "country": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "street", "postcode", "country"
                        ]
                    }
                },
                "properties": {
                    "address": {
                        "$ref": "#/definitions/addressItem"
                    }
                },
                "required" : [
                    "address"
                ]
            }
```

Should dredd/Gavel be supporting these JSON Schema features?

**Comment by stianborgesen** [comment]
+1

**Comment by netmilk** [comment]
Hi @jessedc @stianborgesen,

this should work, Dredd/Gavel should support both Json Schema v3 and v4. This is a v4 feature, but the functionality in Dredd depends on underlaying JSON schema validator. I suspect it's a bug or feature of this validator. I'll investigate further...

**Comment by joaosa** [comment]
I am also experiencing this. Any news? :)

**Comment by honzajavorek** [comment]
@joaosa this is the issue we're solving in https://github.com/apiaryio/gavel.js/issues/25, right?

**Comment by joaosa** [comment]
@honzajavorek yes that seems to be the case. Must've mixed the issues

**Comment by honzajavorek** [comment]
No problem, just linking it together

**Comment by honzajavorek** [comment]
I think this should be fixed by #767 and will be in the next Dredd release, thanks to @joaosa's work on Gavel.js!

**Comment by mrname** [comment]
Does #767 also address this issue for swagger specifications? I would assume so, since I am using swagger 2.0 which utilizes json schema draft 4.

Only asking because I just installed from master and seem to be having this problem still.

**Comment by honzajavorek** [comment]
@mrname Good! I'm glad it works.

**Comment by honzajavorek** [comment]
Should be fixed in Dredd v3.4.2.
